#!/usr/bin/env bash

# suicide on error
set -e

# move to location of this script
# https://stackoverflow.com/a/4774063/3637404
path_of_this_script="$(cd "$(dirname "$0")"; pwd -P )"
cd "${path_of_this_script}"

bemacs=${EMACS:-emacs}

$bemacs -Q -batch \
	-l test/setup-unit-tests.el \
	-l ./evil-python-movement.el \
	-l test/evil-python-movement-unit-tests.el \
	-f ert-run-tests-batch-and-exit
